language: en_core_web_md
pipeline:
- name: SpacyNLP
- name: SpacyTokenizer
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: bert-base-multilingual-uncased
  cache_dir: null
- name: RegexFeaturizer
  use_word_boundaries: true
- name: DIETClassifier
  epochs: 100
  model_confidence: linear_norm
  constrain_similarities: true
- name: EntitySynonymMapper
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 150
- name: RulePolicy
